Bug fix galore
dyc3/d6-survey-service pull request #162
Opened 2023-04-12 18:37 UTC by nick-dimeglio

Essentially ran through a few known issues:

1) Weird behavior of small "X" buttons on the survey edit page is now fixed.
2) Event listener is properly removed on the survey respond page to prevent site from prompting user about not leaving after survey has been submitted.

Closes #159

2023-04-12 21:57 UTC, dyc3 requested changes

2023-04-12 21:57 UTC, dyc3 commented on packages/frontend/src/routes/survey/[slug]/respond/+page.svelte
> +				}
i would prefer it if there was some sort of "page nav" event we could listen for instead.

2023-04-12 21:57 UTC, dyc3 commented on packages/frontend/src/routes/survey/[slug]/respond/+page.svelte
> +				window.removeEventListener('beforeunload', window.onbeforeunload);
also, you do it twice?

2023-04-12 21:57 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +
nit: extraneous newline

2023-04-17 16:23 UTC, nick-dimeglio commented on packages/frontend/src/routes/survey/[slug]/respond/+page.svelte
> +				}
If you have an event listener that you have in mind, I can change this, but as far as I can tell, onbeforeunload is the standard way to handle people leaving the page. A quick canvas online doesn't really show any other suitable event listener that will handle all of the possible page closures.

Here is a good link I found on it: https://stackoverflow.com/questions/15925251/trigger-an-event-when-user-navigates-away

2023-04-17 16:33 UTC, nick-dimeglio commented
> 

So you'd like a test confirming that no dialog box appears once the survey is created?

2023-04-17 16:35 UTC, dyc3 commented
Yes

2023-04-19 06:49 UTC, nick-dimeglio commented on packages/frontend/src/routes/survey/[slug]/respond/+page.svelte
> +				}
I looked into beforeNavigate and fiddled with it for an hour to try to get something up and working with it, but there seems to be huge issues with implementing it for some reason. I can try again during the lab today and explain what I mean better.

2023-04-19 17:21 UTC, dyc3 approved these changes

2023-04-19 17:34 UTC, dyc3 commented
Merging because the test failures are unrelated to the changes in this PR.

2023-04-19 17:34 UTC, merged