Adding feature to reorder questions
dyc3/d6-survey-service pull request #176
Opened 2023-04-19 19:38 UTC by zutingc

- Buttons to move questions up and down respectively by changing their index in the questions array.
- Currently unable to retrieve id to determine the current question's index.

2023-04-19 20:18 UTC, dyc3 requested changes

2023-04-19 20:18 UTC, dyc3 commented on packages/frontend/src/lib/QuestionsEditor.svelte
> +	function swapIndex(increment : number) {
This needs to be something like
```suggestion
	function move(oldIndex: number, newIndex: number) {
```

2023-04-20 20:00 UTC, dyc3 requested changes

2023-04-21 18:39 UTC, nick-dimeglio commented
I was really overcomplicating the array logic and looked at and ended up using yours when implementing in into #178 .

2023-04-25 11:55 UTC, dyc3 commented
Closing this in favor of #178

2023-04-25 11:55 UTC, closed without merging