Drag & drop
dyc3/d6-survey-service pull request #178
Opened 2023-04-21 18:38 UTC by nick-dimeglio

This is allows for items in a survey being edited to be reordered using drag and drop functionality. It is fully functional as is, however, the items only work if they are dragged to another item's textbox and when they get highlighted is super wonky. It works and updates the questions array to be saved, but the UI bugs need to be fixed before merging.

2023-04-25 11:54 UTC, dyc3 requested changes
Yeah something's wrong here.

![image](https://user-images.githubusercontent.com/1808807/234265591-f73249fb-10c1-422c-b2de-3a9583035ce3.png)

Can you make it so that you click and drag a handle and not the entire question? The UI doesn't really indicate you can click and drag. see https://stackoverflow.com/questions/26283661/drag-drop-with-handle and https://www.nngroup.com/articles/drag-drop/

 Maybe we could have a sidebar with a more compact list of questions instead to make reordering questions easier.

2023-04-25 11:54 UTC, dyc3 commented on packages/frontend/src/lib/Draggable.svelte
> +	import { add_classes, toggle_class } from 'svelte/internal';
nit: unused imports

2023-04-25 11:54 UTC, dyc3 commented on packages/frontend/src/lib/Draggable.svelte
> +	const dragstart = (
prefer `function` rather that anon funcs

2023-04-25 11:54 UTC, dyc3 commented on packages/frontend/src/lib/Draggable.svelte
> +		console.log(event);
nit: remove your console logs

2023-04-25 11:54 UTC, dyc3 commented on packages/frontend/src/lib/QuestionsEditor.svelte
> +		questions[newIndex] = tempQ;
This is a swap, not a move. It only works for items that are right next to each other.

For example, with this implementation
```
# move B to 0
A, B, C -> B, A, C # this works

# move C to 0
A, B, C -> C, B, A # this is undesired behavior!
```

What it should look like:
```
# move C to 0
A, B, C -> C, A, B
```

This is something you should abstract into a utility function that works on any given array, and write a unit test for.

2023-04-26 19:43 UTC, nick-dimeglio commented
All issues addressed, only issue not addressed is how to see all questions when dragging and dropping. I have added that to its own issue as that is a rather large task.

2023-04-27 20:45 UTC, dyc3 requested changes

2023-04-27 20:45 UTC, dyc3 commented on packages/frontend/src/lib/functions/arraySwap.ts
nit: move from `lib/functions/arraySwap.ts` to `lib/arrayutils.ts`.

2023-04-27 20:45 UTC, dyc3 commented on packages/frontend/src/lib/functions/arraySwap.ts
> +export function arraySwap(oldIndex: number, newIndex: number, array: any[]) {
nit: This is not a swap. Rename it to `move`, and make `array` the first argument.

2023-04-27 20:45 UTC, dyc3 commented on packages/frontend/src/lib/functions/arraySwap.ts
> +export function arraySwap(oldIndex: number, newIndex: number, array: any[]) {
to fix the lint:
```suggestion
export function arraySwap(oldIndex: number, newIndex: number, array: unknown[]) {
```

2023-04-27 20:45 UTC, dyc3 commented on packages/frontend/src/logic.test.ts
nit: put this file next to `arrayutils.ts` and call it `arrayutils.test.ts`.

2023-04-27 20:45 UTC, dyc3 commented on packages/frontend/src/lib/functions/arraySwap.ts
> +	}
Any reason why this doesn't work? https://github.com/dyc3/opentogethertube/blob/79879712cd83f1326b0bdaf461a3333fb71a020e/server/videoqueue.ts#L110

2023-04-27 20:45 UTC, dyc3 commented on packages/frontend/src/logic.test.ts
> +describe('Ensuring array swap logic works', () => {
nit
```suggestion
describe('arrayutils.move', () => {
```

2023-05-01 06:27 UTC, nick-dimeglio commented on packages/frontend/src/lib/functions/arraySwap.ts
> +	}
It might just be the late night brain fog but that wasn't working right for me and messed up the tests.

2023-05-01 06:44 UTC, nick-dimeglio commented on packages/frontend/src/lib/functions/arraySwap.ts
> +export function arraySwap(oldIndex: number, newIndex: number, array: any[]) {
This throws the error that SurveyQuestions type is not assignable to unknown[] in the QuestionsEditor. I know somewhere it has to get specified but I don't want to toy with types without making sure I'm not messing with anything first.

2023-05-01 06:45 UTC, nick-dimeglio commented
For some reason, without changing anything in the file, this error began appearing in the tsconfig.json file:


Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

2023-05-01 10:40 UTC, dyc3 commented on packages/frontend/src/lib/functions/arraySwap.ts
> +	}
Worked for me. Pushed a commit to fix it.

2023-05-01 10:41 UTC, dyc3 approved these changes

2023-05-01 10:45 UTC, merged