Styled buttons and mysurveys page with a good foundation.
dyc3/d6-survey-service pull request #54
Opened 2023-02-22 01:03 UTC by nick-dimeglio

Still need to add hover effects but I figure that is something to touch up at the end. Closes #35

2023-02-22 14:40 UTC, dyc3 requested changes
There's a lot of unnecessary repetition here.

- Missing a `danger` style for buttons. We need it for the delete buttons on `/mysurveys`

2023-02-22 14:40 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		border: #426881 3px solid;
This does not make the border gradient, as we discussed. There is no CSS that is able to do it, so you have to make a wrapper element have the gradient, and an inner element cover it up so it looks like it's bordered. See https://css-tricks.com/gradient-borders-in-css/

2023-02-22 14:40 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		background: linear-gradient(90deg, rgba(66, 104, 129, 1) 0%, rgba(65, 128, 83, 1) 100%);
move values to scss variables, and put them in a different file so we can use them across the app

2023-02-22 14:40 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		color: #426881;
move values to scss variables

2023-02-22 14:40 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		color: #fff;
- move values to scss variables
- this makes the primary styled button exactly the same as all the other buttons

2023-02-22 14:40 UTC, dyc3 commented on packages/frontend/src/routes/mysurveys/+page.svelte
> +		font-family: 'DM Sans', sans-serif;
move to scss variables

2023-02-22 17:38 UTC, nick-dimeglio commented on packages/frontend/src/lib/ui/Button.svelte
> +		border: #426881 3px solid;
As I was implementing that exact trick, it ends up making things a bit unnecessarily complicated in my opinion. I will go over with you in person today what I mean, but based unless I were to remove every part of the components and start from scratch the current layout is a bit finicky for implementing it.

2023-02-22 18:46 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		<button class={classes} aria-pressed={pressed} on:click={handleClick}>
This hierarchy is making your CSS more verbose than it needs to be. It also causes the very edges of the buttons to not be clickable, but they should, because the entire bounding box of the button should be clickable.

Here's what I recommend instead:
```svelte
<button class={classes} ... >
	<div class="surface">
```
Where `button` has the gradient background, and `.surface` has the same background as the page.

This would then let you do something like this:
```scss
$btn-active-text-color: #fff;
$btn-active-surface-color: transparent;

button:active, [aria-pressed=true] {
    .surface {
        color: $btn-active-text-color;
        background: $btn-active-surface-color;
    }
}
```

2023-02-22 21:51 UTC, nick-dimeglio commented on packages/frontend/src/lib/ui/Button.svelte
> +		<button class={classes} aria-pressed={pressed} on:click={handleClick}>
Had to make it a bit more complicated to swap the styles around for danger buttons but I got something working that isn't too complex.

2023-02-23 00:30 UTC, dyc3 requested changes
Technically better, but you need to think about how to minimize the amount of CSS you are using. CSS is really hard to maintain, and really hard to do right. The less we have of it the better.

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
>  	}
redundant

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
>  	}
redundant

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		}
```suggestion
		.surface{
			background: transparent;
		}
```

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +	$: classes = `kind-${kind} wrapkind-${kind}`;
unused class
```suggestion
	$: classes = `kind-${kind}`;
```

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +	$: surfaceclasses = `surface sz-${size} innerkind-${kind}`
You shouldn't need this, move the size class back to `classes`

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		<div class={surfaceclasses} aria-pressed={pressed}>
```suggestion
	<button class={classes} on:click={handleClick} aria-pressed={pressed}>
		<div class="surface">
```

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +	}
Primary and default need to look different. It's up to you to determine what that looks like, but they need to be different.

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> + 	 	padding: 3px;
You should have a variable `$btn-border-size` defined above in this file that you use for this value.

Also, this might make more sense as `margin` on `.surface`.

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		border-radius: 3px;
You should have a variable for border radius, and it needs to match the outer element's border radius to maintain a constant line width.

2023-02-23 00:30 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +		background: $main-red;
duplicate rule

2023-02-24 22:34 UTC, nick-dimeglio commented on packages/frontend/src/lib/ui/Button.svelte
> +		border-radius: 3px;
It cannot match the outer element's radius as the internal box is smaller than the external box leading to it looking very off. I had this issue in past projects and it must be a bit smaller on the internal box for it to look natural.

2023-02-24 22:36 UTC, nick-dimeglio commented on packages/frontend/src/lib/ui/Button.svelte
> +	}
I'm not quite sure why we need the two types? What is primary intended for? Whatever use case you have in mind will determine how I swap it up; I can make it a bolder text perhaps.

2023-02-25 14:10 UTC, dyc3 commented on packages/frontend/src/lib/ui/Button.svelte
> +	}
Continue this in https://github.com/dyc3/d6-survey-service/issues/73

2023-02-25 14:16 UTC, dyc3 approved these changes

2023-02-25 14:16 UTC, merged