Add login page
dyc3/d6-survey-service pull request #60
Opened 2023-02-22 20:07 UTC by zutingc

- initial test
- frontend framework
- add login page

2023-02-22 20:50 UTC, dyc3 requested changes
You'll need to make it so that it performs a page navigation to `/mysurveys` if log in is successful. 

Also, please remove `package-lock.json`.

2023-02-22 20:50 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +		}
Both register and login have the exact same response, so you can deduplicate handling the response here by moving it into a function:

Should look something like this:
```ts
function handleLogin(resp: ApiResponse<UserToken>) {}
```

2023-02-22 20:50 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +	let response ='';
nit: unused var

2023-02-24 17:52 UTC, dyc3 requested changes
Some of the stuff in my previous review was not fixed.

Also, please remove `package-lock.json`

2023-02-24 17:52 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +				console.log(error);
`response` not set here?

2023-02-24 17:52 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +				window.location.href = '/mysurveys';
This will force the browser to do a full page navigation, which is a lot slower than having svelte handle the navigation.

You'll need to call this function instead:
```ts
import { goto } from '$app/navigation';
```

2023-02-24 17:52 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +		console.log('hi');
unnecessary log

2023-02-24 17:52 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +		}
Per my previous review, deduplicate your code here.

2023-02-24 17:52 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +				jwt.login(resp.value.token);
A successful user registration also implies that they are now logged in, but you don't navigate to the my surveys page.

2023-02-24 17:52 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +			<Tab style="background-color: white; border: 0px;"><Button toggleable={true}>Register</Button></Tab>
I think using `Button` here is making the UI feel kinda janky. Remove the styling and `Button` here, and we'll have @nick-dimeglio make a pass at styling this when this is merged.

2023-02-24 18:47 UTC, zutingc commented on packages/frontend/src/routes/login/+page.svelte
> +			<Tab style="background-color: white; border: 0px;"><Button toggleable={true}>Register</Button></Tab>
I've removed the toggleable since that makes it quite janky but kept button so that we can have an idea of how it should look like. In the future, it may be good to see if we could stylize the default Tab buttons and have them toggle on/off like a switch button.

2023-02-24 19:19 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +			<Tab style="background-color: white; border: 0px;"><Button toggleable={true}>Register</Button></Tab>
We already have an idea of what it should look like, it's in our UI mock up. Please remove `Button`.

2023-02-24 21:28 UTC, zutingc reviewed
Suggestions reviewed and implemented. Is there anything else?

2023-02-25 13:13 UTC, dyc3 requested changes
You still didn't remove `package-lock.json`.

2023-02-25 13:13 UTC, dyc3 commented on package.json
> +		"@headlessui/tailwindcss": "^0.1.2"
1. This is the wrong `package.json` to pull in dependencies with.
2. It doesn't appear we are using `@headlessui/tailwindcss`

2023-02-25 13:13 UTC, dyc3 commented on packages/frontend/src/routes/login/+page.svelte
> +		}
You didn't do anything with the error here, it should at least be printed in the console.

2023-02-25 13:21 UTC, dyc3 approved these changes

2023-02-25 13:25 UTC, merged